/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhotosFromPanel_Flickr.java
 *
 * Created on 21-Dec-2011, 19:08:31
 */

package uk.co.akademy.PhotoShow;

/**
 *
 * @author matthew
 */
public class PhotosFromPanel_Flickr extends AbstractPhotosFromPanel {

    /** Creates new form PhotosFromPanel_Flickr */
    public PhotosFromPanel_Flickr() {
        initComponents();

		this.setName( "Flickr" );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        photoCountSpinner = new javax.swing.JSpinner();
        photoCountLabel = new javax.swing.JLabel();
        setsLabel = new javax.swing.JLabel();
        userTokenLabel = new javax.swing.JLabel();
        userTokenTextField = new javax.swing.JTextField();
        apiSecretTextField = new javax.swing.JTextField();
        apiSecretLabel = new javax.swing.JLabel();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyTextField = new javax.swing.JTextField();
        setsTextField = new javax.swing.JTextField();

        updateButton.setText("Update now");
        updateButton.setEnabled(false);

        photoCountLabel.setText("Photo Count");

        setsLabel.setText("Sets");

        userTokenLabel.setText("User Token");

        apiSecretLabel.setText("API Secret");

        apiKeyLabel.setText("API Key");

        apiKeyTextField.setName("apiKeyTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apiKeyLabel)
                    .addComponent(apiSecretLabel)
                    .addComponent(userTokenLabel)
                    .addComponent(setsLabel)
                    .addComponent(photoCountLabel))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(apiSecretTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(userTokenTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiKeyLabel)
                    .addComponent(apiKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apiSecretTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiSecretLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTokenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTokenLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoCountLabel)
                    .addComponent(photoCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JTextField apiKeyTextField;
    private javax.swing.JLabel apiSecretLabel;
    private javax.swing.JTextField apiSecretTextField;
    private javax.swing.JLabel photoCountLabel;
    private javax.swing.JSpinner photoCountSpinner;
    private javax.swing.JLabel setsLabel;
    private javax.swing.JTextField setsTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userTokenLabel;
    private javax.swing.JTextField userTokenTextField;
    // End of variables declaration//GEN-END:variables

	@Override
	protected boolean initialise(PropertyFetcher properties) {

		String apiKey = properties.getProperty("flickr.apiKey");
		apiKeyTextField.setText(apiKey);
		
		String apiSecret = properties.getProperty("flickr.apiSecret");
		apiSecretTextField.setText(apiSecret);

		String userToken = properties.getProperty("flickr.userToken");
		if( userToken.isEmpty() )
			userTokenTextField.setText( "14280458@N05" );
		else
			userTokenTextField.setText( userToken );

		String sets = properties.getProperty("flickr.photosets");
		setsTextField.setText(sets);

		String photoCount = properties.getProperty("flickr.photoCount");
		photoCountSpinner.setValue( Integer.parseInt( photoCount ) );

		return true;
	}

	@Override
	protected void updateProperties() {
		Program.setProperty( "flickr.apiKey", apiKeyTextField.getText() );
		Program.setProperty( "flickr.apiSecret", apiSecretTextField.getText() );

		Program.setProperty( "flickr.userToken", userTokenTextField.getText() );

		Program.setProperty( "flickr.photosets", setsTextField.getText() );

		Program.setProperty( "flickr.photoCount", photoCountSpinner.getValue().toString() );
	}

}
