/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhotosFromPanel_General.java
 *
 * Created on 21-Dec-2011, 22:45:49
 */

package uk.co.akademy.PhotoShow;

/**
 *
 * @author matthew
 */
public class PhotosFromPanel_General extends AbstractPhotosFromPanel {

	/*private String general_proxyHost= "";
	private int general_photoShowTime = 10000;
	private int general_proxyPort = 8080;*/

    /** Creates new form PhotosFromPanel_General */
    public PhotosFromPanel_General() {
        initComponents();

		this.setName( "General" );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proxyHostTextField = new javax.swing.JTextField();
        photoTimeSpinner = new javax.swing.JSpinner();
        photoTimeLabel = new javax.swing.JLabel();
        proxyPortTextField = new javax.swing.JTextField();
        proxyHostLabel = new javax.swing.JLabel();
        proxyPortLabel = new javax.swing.JLabel();

        photoTimeLabel.setText("Photo show time (ms)");

        proxyHostLabel.setText("Proxy host");

        proxyPortLabel.setText("Proxy port");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(photoTimeLabel)
                        .addGap(38, 38, 38)
                        .addComponent(photoTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proxyHostLabel)
                            .addComponent(proxyPortLabel))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proxyPortTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(proxyHostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoTimeLabel)
                    .addComponent(photoTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyHostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proxyHostLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proxyPortLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	@Override
	boolean initialise(PropertyFetcher properties) {

		photoTimeSpinner.setValue( Integer.parseInt( properties.getProperty("general.photoShowTime") ) );
		proxyHostTextField.setText( properties.getProperty("general.proxyHost") );
		proxyPortTextField.setText( properties.getProperty("general.proxyPort") );

		return true;
	}

	@Override
	void updateProperties() {
		Program.setProperty( "general.photoShowTime", photoTimeSpinner.getValue().toString() );
		Program.setProperty( "general.proxyHost", proxyHostTextField.getText() );
		Program.setProperty( "general.proxyPort", proxyPortTextField.getText() );
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photoTimeLabel;
    private javax.swing.JSpinner photoTimeSpinner;
    private javax.swing.JLabel proxyHostLabel;
    private javax.swing.JTextField proxyHostTextField;
    private javax.swing.JLabel proxyPortLabel;
    private javax.swing.JTextField proxyPortTextField;
    // End of variables declaration//GEN-END:variables

}
