/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhotosFromPanel_Example.java
 *
 * Created on 17-Aug-2012, 00:23:18
 */

package uk.co.akademy.PhotosFrom.Example;

import uk.co.akademy.PhotoShow.AbstractPhotosFromPanel;
import uk.co.akademy.PhotoShow.PropertyFetcher;

/**
 *
 * @author matthew
 */
public class PhotosFromPanel_Example extends AbstractPhotosFromPanel {

    /** Creates new form PhotosFromPanel_Example */
    public PhotosFromPanel_Example() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("There's nothing to set in the example.");

        jLabel2.setText("TODO: Add an example settings which is stored in the properties");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	@Override
	public boolean initialise(PropertyFetcher properties) {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public void updateProperties() {
		throw new UnsupportedOperationException("Not supported yet.");
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
